language: python
python:
  - "3.6"
sudo: enabled
before_install:
  - npm install -g npm@latest
install:
  - make setup-travis
  - pip install codecov
script: make test
after_success:
  - codecov
branches:
  only:
    - master
    - develop
services:
  - postgresql
addons:
  # NOTE Travis is not compatible with postgres version 10+ (23/11/2018)
  postgresql: "9.6"
