# Generated by Django 2.1.2 on 2018-10-18 11:50

from django.db import migrations, models

import VLE.utils.file_handling
import VLE.utils.storage


class Migration(migrations.Migration):

    dependencies = [
        ('VLE', '0006_auto_20181014_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(null=True, storage=VLE.utils.storage.OverwriteStorage(), upload_to=VLE.utils.file_handling.get_profile_picture_path),
        ),
    ]
