# Generated by Django 2.1.2 on 2018-10-18 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VLE', '0007_auto_20181018_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lti_image',
            field=models.TextField(null=True),
        ),
    ]
