# Generated by Django 2.1.2 on 2018-10-21 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VLE', '0006_can_view_assignment_journals_rename'),
        ('VLE', '0008_user_lti_image'),
    ]

    operations = [
    ]
