# Generated by Django 2.1.2 on 2018-10-27 14:03

import django.utils.timezone
from django.db import migrations, models


def combine_names(apps, schema_editor):
    User = apps.get_model('VLE', 'User')
    for user in User.objects.all():
        user.full_name = '%s %s' % (user.first_name, user.last_name)
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('VLE', '0009_add_selection_field'),
    ]

    operations = [
        migrations.RunPython(combine_names),
        migrations.RenameField('comment', 'timestamp', 'creation_date'),
        migrations.RenameField('entry', 'createdate', 'creation_date'),
        migrations.AlterField(
            model_name='comment',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entry',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userfile',
            name='last_edited',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='last_edited',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entry',
            name='last_edited',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userfile',
            name='creation_date',
            field=models.DateTimeField(editable=False),
        ),
    ]
