# Generated by Django 2.1.2 on 2018-10-28 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VLE', '0010_auto_20181027_1403'),
        ('VLE', '0010_auto_20181028_1133'),
    ]

    operations = [
    ]
