# Generated by Django 2.1.2 on 2019-01-02 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VLE', '0011_merge_20181028_1204'),
        ('VLE', '0012_auto_20181211_2201'),
    ]

    operations = [
    ]
